BENCH First test of different method of decoding.
----------------------------------------------------------
BENCHMARK_MARKER_DO_NOT_CHANGE
----------------------------------------------------------

TEST BENCHMARKS
?   	github.com/gconnell/gopacket	[no test files]
?   	github.com/gconnell/gopacket/layers	[no test files]
?   	github.com/gconnell/gopacket/pcap	[no test files]
?   	github.com/gconnell/gopacket/pfring	[no test files]

PCAP BENCHMARK
Reading file once through to hopefully cache most of it
Read in file /tmp/gopacket_benchmark.pcap , total of 341401548 bytes
1/10: Opening file "/tmp/gopacket_benchmark.pcap" for read
Reading packet data into memory: 1237119 packets in 902.455ms, 729ns per packet
Read in 1237119 packets in 2.95565s, 2.389us per packet
Time to both read and process: 3.858155s
2/10: Opening file "/tmp/gopacket_benchmark.pcap" for read
Reading packet data into memory: 1237119 packets in 749.528ms, 605ns per packet
Read in 1237119 packets in 2.783619s, 2.25us per packet
Time to both read and process: 3.533181s
3/10: Opening file "/tmp/gopacket_benchmark.pcap" for read
Reading packet data into memory: 1237119 packets in 910.781ms, 736ns per packet
Read in 1237119 packets in 2.816479s, 2.276us per packet
Time to both read and process: 3.727295s
4/10: Opening file "/tmp/gopacket_benchmark.pcap" for read
Reading packet data into memory: 1237119 packets in 804.526ms, 650ns per packet
Read in 1237119 packets in 3.006795s, 2.43us per packet
Time to both read and process: 3.811356s
5/10: Opening file "/tmp/gopacket_benchmark.pcap" for read
Reading packet data into memory: 1237119 packets in 687.561ms, 555ns per packet
Read in 1237119 packets in 2.933418s, 2.371us per packet
Time to both read and process: 3.621012s
6/10: Opening file "/tmp/gopacket_benchmark.pcap" for read
Reading packet data into memory: 1237119 packets in 693.244ms, 560ns per packet
Read in 1237119 packets in 2.918476s, 2.359us per packet
Time to both read and process: 3.611753s
7/10: Opening file "/tmp/gopacket_benchmark.pcap" for read
Reading packet data into memory: 1237119 packets in 704.33ms, 569ns per packet
Read in 1237119 packets in 2.883663s, 2.33us per packet
Time to both read and process: 3.588027s
8/10: Opening file "/tmp/gopacket_benchmark.pcap" for read
Reading packet data into memory: 1237119 packets in 728.129ms, 588ns per packet
Read in 1237119 packets in 2.851865s, 2.305us per packet
Time to both read and process: 3.580029s
9/10: Opening file "/tmp/gopacket_benchmark.pcap" for read
Reading packet data into memory: 1237119 packets in 749.869ms, 606ns per packet
Read in 1237119 packets in 2.796343s, 2.26us per packet
Time to both read and process: 3.546246s
10/10: Opening file "/tmp/gopacket_benchmark.pcap" for read
Reading packet data into memory: 1237119 packets in 780.672ms, 631ns per packet
Read in 1237119 packets in 3.049694s, 2.465us per packet
Time to both read and process: 3.830399s
----------------------------------------------------------
BENCHMARKING AGAINST COMMIT 626160298e5e699b6f49e655eebce7f345f05c90
----------------------------------------------------------

OLD TEST BENCHMARKS
?   	github.com/gconnell/gopacket	[no test files]
?   	github.com/gconnell/gopacket/layers	[no test files]
?   	github.com/gconnell/gopacket/pcap	[no test files]
?   	github.com/gconnell/gopacket/pfring	[no test files]

OLD PCAP BENCHMARK
# github.com/gconnell/gopacket/layers
layers/layertypes.go:10: undefined: decodeARP
layers/layertypes.go:11: undefined: decodeCiscoDiscovery
layers/layertypes.go:12: undefined: decodeEthernetCTP
layers/layertypes.go:15: undefined: decodeDot1Q
layers/layertypes.go:16: undefined: decodeEtherIP
layers/layertypes.go:18: undefined: decodeGRE
layers/layertypes.go:19: undefined: decodeICMP
layers/layertypes.go:21: undefined: decodeIPv6
layers/layertypes.go:22: undefined: decodeLLC
layers/layertypes.go:23: undefined: decodeSNAP
layers/layertypes.go:23: too many errors